### ISSUE TITLE
Compile Errors and solutions

### ISSUE THREAD

**Issue by Niceguy1337** [Asmadeuxx/mod-promotion-AzerothCore-#1]
Fixes
486        QueryResult result = CharacterDatabase.Query("SELECT COUNT(`guid`) FROM `characters` WHERE `account`=%u", accountID);
488        uint32 pjts = fields[0].Get< uint32 >(); <--- Remove Spaces (somehow it doesnt appear)
508        creature->Whisper("You Got Your Promotion!", LANG_UNIVERSAL, player);

Not Fixed
"LoadMore" is not a member of "ConfigMgr".	modules	G:\WoW Server\AzerothCoreNew\Core\modules\mod-promotion-AzerothCore\src\mod_promotion.cpp	606	
"LoadMore" is not a member of "ConfigMgr".	modules	G:\WoW Server\AzerothCoreNew\Core\modules\mod-promotion-AzerothCore\src\mod_promotion.cpp	607

**Comment by Asmadeuxx** [comment]
I will be uploading the fixes, and updating the module.

**Comment by Asmadeuxx** [comment]
[b086e6c](https://github.com/Asmadeuxx/mod-promotion-AzerothCore-/commit/b086e6c92b3fde6da3011da77367e72f89d7da2e)
